In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from wrangle import wrangle_da
from exploration import explore_df, split_data
from modeling import confusion, random_forest_models

In [42]:
# importing random forest classifier from assemble module
from sklearn.ensemble import RandomForestClassifier

In [63]:
import scipy.stats as stats

In [4]:
df = explore_df()

In [5]:
df

       court_number arrest_date  ... weekend low_high_court_num
0          11000113  2011-01-01  ...       1               high
1          11000406  2011-01-04  ...       0               high
2          11000242  2011-01-03  ...       0               high
3          11001323  2011-01-13  ...       0               high
4          11001786  2011-01-17  ...       0               high
...             ...         ...  ...     ...                ...
75807      22000478  2022-01-14  ...       0               high
75808      22001333  2022-02-07  ...       0               high
75809      22005865  2022-06-17  ...       0               high
75810      16000640  2016-01-10  ...       1               high
75811      17006165  2017-04-24  ...       0               high

[75812 rows x 11 columns]

In [6]:
df.drop(columns=['low_high_court_num', 'court_number', 'arrest_date', 'weekend'])

      arresting_agency crime_type booked_case_type  ... da_action_taken  year  month
0                 SFPD    Robbery           Felony  ...      Discharged  2011      1
1                 SFPD    Robbery           Felony  ...      Discharged  2011      1
2                 SFPD    Robbery           Felony  ...      Discharged  2011      1
3                 SFPD    Robbery           Felony  ...      Discharged  2011      1
4                 SFPD    Robbery           Felony  ...      Discharged  2011      1
...                ...        ...              ...  ...             ...   ...    ...
75807             SFPD   Burglary      Misd Arrest  ...   Charges Filed  2022      1
75808             SFSD   Burglary      Misd Arrest  ...   Charges Filed  2022      2
75809             SFPD   Burglary      Misd Arrest  ...   Charges Filed  2022      6
75810             SFPD   Burglary      Misd Arrest  ...   Charges Filed  2016      1
75811             SFPD   Burglary      Misd Arrest  ...   Charges Filed  2017      4

[75812 rows x 7 columns]

In [7]:
df = df.drop(columns=['low_high_court_num', 'court_number', 'arrest_date', 'weekend'])

In [8]:
df.da_action_taken.map({'Discharged': 0, 'Charges Filed': 1})

0        0
1        0
2        0
3        0
4        0
        ..
75807    1
75808    1
75809    1
75810    1
75811    1
Name: da_action_taken, Length: 75812, dtype: category
Categories (2, int64): [1 < 0]

In [9]:
df.da_action_taken = df.da_action_taken.map({'Discharged': 0, 'Charges Filed': 1})

In [10]:
df.columns.to_list()

['arresting_agency',
 'crime_type',
 'booked_case_type',
 'dv_case',
 'da_action_taken',
 'year',
 'month']

In [11]:
X_cols = ['arresting_agency',
 'crime_type',
 'booked_case_type',
 'dv_case',
 'year',
 'month']

In [12]:
y_col = df['da_action_taken']

In [13]:
df

      arresting_agency crime_type booked_case_type  ... da_action_taken  year  month
0                 SFPD    Robbery           Felony  ...               0  2011      1
1                 SFPD    Robbery           Felony  ...               0  2011      1
2                 SFPD    Robbery           Felony  ...               0  2011      1
3                 SFPD    Robbery           Felony  ...               0  2011      1
4                 SFPD    Robbery           Felony  ...               0  2011      1
...                ...        ...              ...  ...             ...   ...    ...
75807             SFPD   Burglary      Misd Arrest  ...               1  2022      1
75808             SFSD   Burglary      Misd Arrest  ...               1  2022      2
75809             SFPD   Burglary      Misd Arrest  ...               1  2022      6
75810             SFPD   Burglary      Misd Arrest  ...               1  2016      1
75811             SFPD   Burglary      Misd Arrest  ...               1  2017      4

[75812 rows x 7 columns]

In [17]:
pd.get_dummies(df, columns=['arresting_agency', 'crime_type', 'booked_case_type', 'dv_case', 'year', 'month'], drop_first=True)

      da_action_taken  arresting_agency_CHP  ...  month_11  month_12
0                   0                     0  ...         0         0
1                   0                     0  ...         0         0
2                   0                     0  ...         0         0
3                   0                     0  ...         0         0
4                   0                     0  ...         0         0
...               ...                   ...  ...       ...       ...
75807               1                     0  ...         0         0
75808               1                     0  ...         0         0
75809               1                     0  ...         0         0
75810               1                     0  ...         0         0
75811               1                     0  ...         0         0

[75812 rows x 34 columns]

In [18]:
df= pd.get_dummies(df, columns=['arresting_agency', 'crime_type', 'booked_case_type', 'dv_case', 'year', 'month'], drop_first=True)

In [19]:
train, validate, test = split_data(df,strat_by='da_action_taken')

Prepared df: (75812, 34)

Train: (45486, 34)
Validate: (15163, 34)
Test: (15163, 34)

In [21]:
df.columns.to_list()

['da_action_taken',
 'arresting_agency_CHP',
 'arresting_agency_SFPD',
 'arresting_agency_SFSD',
 'crime_type_Assault and Battery',
 'crime_type_Burglary',
 'crime_type_DUI',
 'crime_type_Narcotics',
 'crime_type_Robbery',
 'crime_type_Theft',
 'booked_case_type_Misd Arrest',
 'dv_case_Yes',
 'year_2012',
 'year_2013',
 'year_2014',
 'year_2015',
 'year_2016',
 'year_2017',
 'year_2018',
 'year_2019',
 'year_2020',
 'year_2021',
 'year_2022',
 'month_2',
 'month_3',
 'month_4',
 'month_5',
 'month_6',
 'month_7',
 'month_8',
 'month_9',
 'month_10',
 'month_11',
 'month_12']

In [22]:
X_cols = ['arresting_agency_CHP',
 'arresting_agency_SFPD',
 'arresting_agency_SFSD',
 'crime_type_Assault and Battery',
 'crime_type_Burglary',
 'crime_type_DUI',
 'crime_type_Narcotics',
 'crime_type_Robbery',
 'crime_type_Theft',
 'booked_case_type_Misd Arrest',
 'dv_case_Yes',
 'year_2012',
 'year_2013',
 'year_2014',
 'year_2015',
 'year_2016',
 'year_2017',
 'year_2018',
 'year_2019',
 'year_2020',
 'year_2021',
 'year_2022',
 'month_2',
 'month_3',
 'month_4',
 'month_5',
 'month_6',
 'month_7',
 'month_8',
 'month_9',
 'month_10',
 'month_11',
 'month_12']

In [25]:
y_col = ['da_action_taken']

In [26]:
X_train, y_train = train[X_cols], train[y_col]

X_validate, y_validate = validate[X_cols], validate[y_col]

X_test, y_test = test[X_cols], test[y_col]

In [27]:
X_train

       arresting_agency_CHP  arresting_agency_SFPD  ...  month_11  month_12
40829                     0                      1  ...         0         0
68895                     0                      1  ...         0         0
41045                     0                      1  ...         1         0
56700                     0                      1  ...         0         0
2297                      0                      1  ...         0         0
...                     ...                    ...  ...       ...       ...
42092                     0                      0  ...         0         0
28276                     0                      1  ...         0         1
22800                     0                      1  ...         0         0
10457                     0                      1  ...         0         1
48050                     0                      1  ...         0         0

[45486 rows x 33 columns]

In [28]:
y_train

      da_action_taken
40829               1
68895               1
41045               1
56700               0
2297                1
...               ...
42092               1
28276               1
22800               1
10457               0
48050               1

[45486 rows x 1 columns]

In [41]:
y_train.mode().values[0][0]

1

In [43]:
rfc = RandomForestClassifier(random_state=123)

In [45]:
rfc.fit(X_train, y_train.da_action_taken)

RandomForestClassifier(random_state=123)

In [47]:
preds1 = rfc.predict(X_train)

In [57]:
y_train['pred_rfc1'] = preds1

/var/folders/n7/p9r5pxl53g99g0h4q1_h50fr0000gn/T/ipykernel_19301/369692629.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [58]:
y_train

      da_action_taken  pred_rfc1
40829               1          1
68895               1          1
41045               1          1
56700               0          0
2297                1          1
...               ...        ...
42092               1          1
28276               1          0
22800               1          0
10457               0          0
48050               1          1

[45486 rows x 2 columns]

In [59]:
from sklearn.metrics import confusion_matrix

In [60]:
confusion_matrix(y_true= y_train.da_action_taken, y_pred= y_train.pred_rfc1)

array([[11452,  6491],
       [ 4304, 23239]])

In [61]:
TN, FP, FN, TP = confusion_matrix(y_true= y_train.da_action_taken, y_pred= y_train.pred_rfc1).ravel()

In [64]:
confusion(TN, TP, FN, FP)

    _______________________________________________________________________________________

    True Positive = 23239 ---- False Positive = 6491
    True Negative = 11452 ---- False Negative = 4304

    Out of 45486 predictions -- Correct predictions = 34691 (True Pos + True Neg)

    REAL POSITIVE = (TP + FN) = 27543 ---- PREDICTED POSITIVE = (TP + FP) = 29730

    REAL NEGATIVE = (TN + FP) = 17943 ---- PREDICTED NEGATIVE = (TN + FN) = 15756

        Accuracy = 76.27% -->> Correct Predictions / Total Predictions
       Precision = 78.17% -->> True Positive / Predicted Positive
             NPV = 72.68% -->> True Negative / Predicted Negative
          Recall = 84.37% -->> True Positive / Real Positive
     Specificity = 63.82% -->> True Negative / Real Negative
        f1-score = 81.15% -->> Harmonic Mean of Precision and Recall
    _______________________________________________________________________________________

In [65]:
y_train['baseline'] = 1

/var/folders/n7/p9r5pxl53g99g0h4q1_h50fr0000gn/T/ipykernel_19301/1524105747.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [67]:
TN, FP, FN, TP = confusion_matrix(y_true= y_train.da_action_taken, y_pred= y_train.baseline).ravel()

confusion(TN, TP, FN, FP)

    _______________________________________________________________________________________

    True Positive = 27543 ---- False Positive = 17943
    True Negative = 0 ---- False Negative = 0

    Out of 45486 predictions -- Correct predictions = 27543 (True Pos + True Neg)

    REAL POSITIVE = (TP + FN) = 27543 ---- PREDICTED POSITIVE = (TP + FP) = 45486

    REAL NEGATIVE = (TN + FP) = 17943 ---- PREDICTED NEGATIVE = (TN + FN) = 0

        Accuracy = 60.55% -->> Correct Predictions / Total Predictions
       Precision = 60.55% -->> True Positive / Predicted Positive
             NPV = nan% -->> True Negative / Predicted Negative
          Recall = 100.00% -->> True Positive / Real Positive
     Specificity = 0.00% -->> True Negative / Real Negative
        f1-score = 75.43% -->> Harmonic Mean of Precision and Recall
    _______________________________________________________________________________________

/var/folders/n7/p9r5pxl53g99g0h4q1_h50fr0000gn/T/ipykernel_19301/3986803650.py:74: RuntimeWarning:

invalid value encountered in long_scalars

In [68]:
rfc.predict(X_validate)

array([1, 1, 1, ..., 0, 0, 1])

In [70]:
y_validate['pred_rfc1']= rfc.predict(X_validate)

/var/folders/n7/p9r5pxl53g99g0h4q1_h50fr0000gn/T/ipykernel_19301/2030062847.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [72]:
y_validate['baseline'] = 1

/var/folders/n7/p9r5pxl53g99g0h4q1_h50fr0000gn/T/ipykernel_19301/3187294974.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [73]:
TN, FP, FN, TP = confusion_matrix(y_true= y_validate.da_action_taken, y_pred= y_validate.baseline).ravel()

confusion(TN, TP, FN, FP)

    _______________________________________________________________________________________

    True Positive = 9182 ---- False Positive = 5981
    True Negative = 0 ---- False Negative = 0

    Out of 15163 predictions -- Correct predictions = 9182 (True Pos + True Neg)

    REAL POSITIVE = (TP + FN) = 9182 ---- PREDICTED POSITIVE = (TP + FP) = 15163

    REAL NEGATIVE = (TN + FP) = 5981 ---- PREDICTED NEGATIVE = (TN + FN) = 0

        Accuracy = 60.56% -->> Correct Predictions / Total Predictions
       Precision = 60.56% -->> True Positive / Predicted Positive
             NPV = nan% -->> True Negative / Predicted Negative
          Recall = 100.00% -->> True Positive / Real Positive
     Specificity = 0.00% -->> True Negative / Real Negative
        f1-score = 75.43% -->> Harmonic Mean of Precision and Recall
    _______________________________________________________________________________________

/var/folders/n7/p9r5pxl53g99g0h4q1_h50fr0000gn/T/ipykernel_19301/3986803650.py:74: RuntimeWarning:

invalid value encountered in long_scalars

In [ ]:
TN, FP, FN, TP = confusion_matrix(y_true= y_validate.da_action_taken, y_pred= y_validate.pred_rfc1).ravel()

confusion(TN, TP, FN, FP)

    _______________________________________________________________________________________

    True Positive = 7452 ---- False Positive = 2380
    True Negative = 3601 ---- False Negative = 1730

    Out of 15163 predictions -- Correct predictions = 11053 (True Pos + True Neg)

    REAL POSITIVE = (TP + FN) = 9182 ---- PREDICTED POSITIVE = (TP + FP) = 9832

    REAL NEGATIVE = (TN + FP) = 5981 ---- PREDICTED NEGATIVE = (TN + FN) = 5331

        Accuracy = 72.89% -->> Correct Predictions / Total Predictions
       Precision = 75.79% -->> True Positive / Predicted Positive
             NPV = 67.55% -->> True Negative / Predicted Negative
          Recall = 81.16% -->> True Positive / Real Positive
     Specificity = 60.21% -->> True Negative / Real Negative
        f1-score = 78.38% -->> Harmonic Mean of Precision and Recall
    _______________________________________________________________________________________

In [75]:
rfc2 = RandomForestClassifier(random_state=123, min_samples_leaf=5, min_samples_split=5)

In [76]:
rfc2.fit(X_train, y_train.da_action_taken)

RandomForestClassifier(min_samples_leaf=5, min_samples_split=5,
                       random_state=123)

In [77]:
preds2 = rfc2.predict(X_train)

In [78]:
y_train['pred_rfc2'] = preds2

/var/folders/n7/p9r5pxl53g99g0h4q1_h50fr0000gn/T/ipykernel_19301/2865738946.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [79]:
TN, FP, FN, TP = confusion_matrix(y_true= y_train.da_action_taken, y_pred= y_train.pred_rfc2).ravel()

confusion(TN, TP, FN, FP)

    _______________________________________________________________________________________

    True Positive = 23269 ---- False Positive = 7017
    True Negative = 10926 ---- False Negative = 4274

    Out of 45486 predictions -- Correct predictions = 34195 (True Pos + True Neg)

    REAL POSITIVE = (TP + FN) = 27543 ---- PREDICTED POSITIVE = (TP + FP) = 30286

    REAL NEGATIVE = (TN + FP) = 17943 ---- PREDICTED NEGATIVE = (TN + FN) = 15200

        Accuracy = 75.18% -->> Correct Predictions / Total Predictions
       Precision = 76.83% -->> True Positive / Predicted Positive
             NPV = 71.88% -->> True Negative / Predicted Negative
          Recall = 84.48% -->> True Positive / Real Positive
     Specificity = 60.89% -->> True Negative / Real Negative
        f1-score = 80.48% -->> Harmonic Mean of Precision and Recall
    _______________________________________________________________________________________

In [80]:
y_validate['pred_rfc2']= rfc2.predict(X_validate)

/var/folders/n7/p9r5pxl53g99g0h4q1_h50fr0000gn/T/ipykernel_19301/1705682898.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [81]:
TN, FP, FN, TP = confusion_matrix(y_true= y_validate.da_action_taken, y_pred= y_validate.pred_rfc2).ravel()

confusion(TN, TP, FN, FP)

    _______________________________________________________________________________________

    True Positive = 7584 ---- False Positive = 2403
    True Negative = 3578 ---- False Negative = 1598

    Out of 15163 predictions -- Correct predictions = 11162 (True Pos + True Neg)

    REAL POSITIVE = (TP + FN) = 9182 ---- PREDICTED POSITIVE = (TP + FP) = 9987

    REAL NEGATIVE = (TN + FP) = 5981 ---- PREDICTED NEGATIVE = (TN + FN) = 5176

        Accuracy = 73.61% -->> Correct Predictions / Total Predictions
       Precision = 75.94% -->> True Positive / Predicted Positive
             NPV = 69.13% -->> True Negative / Predicted Negative
          Recall = 82.60% -->> True Positive / Real Positive
     Specificity = 59.82% -->> True Negative / Real Negative
        f1-score = 79.13% -->> Harmonic Mean of Precision and Recall
    _______________________________________________________________________________________

In [82]:
y_test['pred_rfc2']= rfc2.predict(X_test)

TN, FP, FN, TP = confusion_matrix(y_true= y_test.da_action_taken, y_pred= y_test.pred_rfc2).ravel()

confusion(TN, TP, FN, FP)

    _______________________________________________________________________________________

    True Positive = 7680 ---- False Positive = 2442
    True Negative = 3539 ---- False Negative = 1502

    Out of 15163 predictions -- Correct predictions = 11219 (True Pos + True Neg)

    REAL POSITIVE = (TP + FN) = 9182 ---- PREDICTED POSITIVE = (TP + FP) = 10122

    REAL NEGATIVE = (TN + FP) = 5981 ---- PREDICTED NEGATIVE = (TN + FN) = 5041

        Accuracy = 73.99% -->> Correct Predictions / Total Predictions
       Precision = 75.87% -->> True Positive / Predicted Positive
             NPV = 70.20% -->> True Negative / Predicted Negative
          Recall = 83.64% -->> True Positive / Real Positive
     Specificity = 59.17% -->> True Negative / Real Negative
        f1-score = 79.57% -->> Harmonic Mean of Precision and Recall
    _______________________________________________________________________________________

/var/folders/n7/p9r5pxl53g99g0h4q1_h50fr0000gn/T/ipykernel_19301/1420971409.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [54]:
def random_forest_models(num_models, rand_st=123, positive=1, max_samp=1.0, trees=100):
    '''
    random_forest_models is a function that:
        
        Takes in:   num_models=  >> The number of rf models 
                                  you want to create  ;dtype(int)
                       rand_st=  >> Random State  
                                  ;dtype(int) = 123 unless specified
                      positive=  >> what is the positive test 
                                  (0 or 1)
                      max_samp=  >> maximum samples per tree
                                  ;dtype(int, float) = (default)1.0
                                  if int: = number of samples
                                  if float: = percentage of total samples
                         trees=  >> n_estimators: number of trees in the forest
        
Assumed variables apply:
    
                  train: training dataset
               validate: validate dataset
                   test: test dataset

                 X_cols = df.columns.drop('target_y').to_list()
                  y_col = 'target_y'

                X_train = train[X_cols]
                y_train = train[y_col]
             X_validate = validate[X_cols]
             y_validate = validate[y_col]
                 X_test = test[X_cols]
                 y_test = test[y_col]
                 
        Returns: a DataFrame with predictions for each model
    '''
    b = 1
    preds = pd.DataFrame({
    'actual': y_train,
    'baseline': b, 
    }, index=[0])
    depth = 11 #num_models * 2 + 1
#     fig, ax = plt.subplot(nrows = num_models,n)
    best = 1
    for i in range(1, num_models+1):
        depth -= 1
        name = f'model_{i}_depth_{depth}'
        
        rf = RandomForestClassifier(random_state = rand_st, 
                                    min_samples_leaf = i, 
                                    max_depth = depth,
                                    max_samples = max_samp,
                                    n_estimators = trees
                                   )
        rf.fit(X_train, y_train)
        
        preds[name] = rf.predict(X_train)
#         val_name = f'{name}_validate'
        TN, FP, FN, TP = confusion_matrix(preds.actual, preds[name]).ravel()
        print(f'\n{name}\n\n {rf}')
        confusion(TN=TN, TP=TP, FN=FN, FP=FP)
        print(f'Validation score is: {rf.score(X_validate, y_validate):.2%}')
        print('______________________________')
#         preds[val_name] = rf.predict(X_val)
#         plt.subplot(i,i,12)
#         plt.title(f'{name} feature importances')
#         plt.barh(X_train.columns, rf.feature_importances_)
#         plt.show
                
    return preds


def confusion(TN, TP, FN, FP):
    acc = (TP+TN)/(TP+TN+FP+FN)
    pre = (TP/(TP+FP))
    NPV = (TN/(TN+FN))
    rec = (TP/(TP+FN))
    spe = (TN/(TN+FP))
    f1s = stats.hmean([(TP/(TP+FP)),(TP/(TP+FN))])
    print(
    f'''
    _______________________________________________________________________________________
    
    True Positive = {TP} ---- False Positive = {FP}
    True Negative = {TN} ---- False Negative = {FN}
    
    Out of {TP+FN+FP+TN} predictions -- Correct predictions = {TP+TN} (True Pos + True Neg) 
    
    REAL POSITIVE = (TP + FN) = {TP+FN} ---- PREDICTED POSITIVE = (TP + FP) = {TP+FP}
    
    REAL NEGATIVE = (TN + FP) = {TN+FP} ---- PREDICTED NEGATIVE = (TN + FN) = {TN+FN}
     
        Accuracy = {acc:.2%} -->> Correct Predictions / Total Predictions
       Precision = {pre:.2%} -->> True Positive / Predicted Positive
             NPV = {NPV:.2%} -->> True Negative / Predicted Negative
          Recall = {rec:.2%} -->> True Positive / Real Positive
     Specificity = {spe:.2%} -->> True Negative / Real Negative
        f1-score = {f1s:.2%} -->> Harmonic Mean of Precision and Recall
    _______________________________________________________________________________________
    '''
    )